name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT : true
      DOTNET_MULTILEVEL_LOOKUP : true

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 7.*
        include-prerelease: True

    # changes the base-tag in index.html from '/' to 'HtmlRaportGenerator' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to HtmlRaportGenerator
      run: sed -i 's/<base href="\/" \/>/<base href="\/HtmlRaportGenerator\/" \/>/g' HtmlRaportGenerator/wwwroot/index.html

    - name: Publish .NET Core Project
      run: dotnet publish ./HtmlRaportGenerator/HtmlRaportGenerator.csproj -c Release -o release

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
