name: Tests

on:
  pull_request:
    branches: [ master ]
env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT : true
      DOTNET_MULTILEVEL_LOOKUP : true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup .NET 6 preview SDK
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 6.*
        include-prerelease: True

    - name: Setup .NET 5 SDK required for Playwright
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.*

    - name: restore project
      run: dotnet restore ./HtmlRaportGenerator.sln

    - name: build project
      run: dotnet build ./HtmlRaportGenerator.sln -c Release --no-restore

    - name: install playwright dotnet tool
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: install playwright
      run: playwright install

    - name: start site
      run: dotnet run --project ./HtmlRaportGenerator/HtmlRaportGenerator.csproj -c Release --no-build --no-restore &

    - name: run tests
      run: dotnet test ./HtmlRaportGenerator.Tests/HtmlRaportGenerator.Tests.csproj -c Release --no-build --no-restore --logger GitHubActions
